server {
    listen 9111;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 10000;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 20057;
    server_name yaman;
    client_max_body_size 10G;

    location / {
        root examples/website1;
        methods GET;
        autoindex on;
        index src/home.html;
    }
}
