server {
    listen 9111;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 10000;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 20057;
    server_name yaman;
    client_max_body_size 10K;



    location / {
        root examples/website1;
        methods GET;
        index src/home.html;
    }
}

server {
    listen 127.0.0.1:8080;
    server_name yaman;
    client_max_body_size 10G;

    location assets
    {
        root examples/website1/assets;
        methods GET;
    }
    location / {
        root examples/website1;
        methods GET;
        autoindex on;
        index src/home.html;
    }
}

server {
    listen 20058;
    server_name redir_test;
    client_max_body_size 10K;

    location /src {
        root examples/website1;
        methods GET;
    }

    location /assets {
        root examples/website1;
        methods GET;
    }

    location / {
        methods GET;
        return 301 /src/home.html;
    }
}

server {
    listen 20059;
    server_name cookie_tester;
    client_max_body_size 1M;

    location / {
        root examples/cookie-showcase;
        methods GET POST;
        cgi_interpreter /bin/python3    .py;
        cgi_interpreter /bin/bash       .sh;
    }
}

