server {
    listen 9111;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 10000;
    server_name localhost;
    client_max_body_size 1M;
}

server {
    listen 20057;
    server_name yaman;
    client_max_body_size 10K;

   

    location / {
        root examples/website1;
        methods GET;
        index src/home.html;
    }
    # location /src
    # {
    #     root examples/website1/src;
    #     methods GET;
    # }
    # location /assets
    # {
    #     root examples/website1/assets;
    #     methods GET;
    # }
}

server {
    listen 127.0.0.1:8080;
    server_name yaman;
    client_max_body_size 10G;

    location assets
    {
        root examples/website1/assets;
        methods GET;
    }
    location / {
        root examples/website1;
        methods GET;
        autoindex on;
        index src/home.html;
    }
}

